### PR TITLE
References #2933 added delay for reportportal connection establish

### PR DESCRIPTION
**Pull request by janardhan-deep**
Description:

- increasing sleep time (10 seconds) after for report portal each request failed
- retry for 10 time

### CODE REVIEW

**Comment by UmangThapliyal** [comment]
@janardhan-deep why the changes are showing all files

**Comment by janardhan-deep** [comment]
> @janardhan-deep why the changes are showing all files

I pushed only one file `index.js`, which I have made changes @UmangThapliyal

**Comment by UmangThapliyal** [comment]
working on the file I can see there are changes where we can either simplify or we can use something else

**Comment by janardhan-deep** [comment]
We'll confirm with @UmangThapliyal and close this PR

**Comment by UmangThapliyal** [comment]
@janardhan-deep closing this pr as it doesnt belong here

**Pull request closed without merging**
